spring:
  application:
    name: NIKITAS-PMS
  cache:
    type: caffeine
  datasource:
    url: jdbc:mysql://localhost:3308/nikithas_pms
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size: 10MB
    


security:
  secretKey: hgdyugdvhxv-ssididgvxhsv-687dhvuygdvghvd

  issuer : triviktech
  expiration : 86400000

sever:
  address: 0.0.0.0
  port: 8080